environment:
  dotnetFormatVersion: 5.0.211103

version: '{build}'
image: Visual Studio 2019

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

# All branches are built by default.

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:
  - ps: dotnet tool update -g dotnet-format --version $env:dotnetFormatVersion

before_build:
  - ps: cd Vynchronizer
  - ps: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

after_test:
  # Check code style.
  - ps: dotnet format "Vynchronizer.sln" --fix-whitespace --fix-style warn --check --verbosity diagnostic

pull_requests:
    do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true
