version: '{build}'
image: Visual Studio 2019

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:
  - ps: dotnet tool update -g dotnet-format

before_build:
  - ps: cd Vynchronizer
  - ps: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

after_test:
  # F# tests does not execute at all.
  # Check code style.
  - ps: dotnet format "Vynchronizer.sln" --fix-whitespace --fix-style warn --check

pull_requests:
    do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true
